version: '3.7'

services:
  mysql1:
    image: mysql:latest
    restart: always
    container_name: product_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
    networks:
      - my_network
    group_add:
      - my_group

  mysql2:
    image: mysql:latest
    restart: always
    container_name: inventory_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventory
    networks:
      - my_network
    group_add:
      - my_group

networks:
  my_network:


