version: '3.7'

services:
  mysql1:
    image: mysql:latest
    restart: always
    container_name: product_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
    ports:
      - 3308:3306


  mysql2:
    image: mysql:latest
    restart: always
    container_name: inventory_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventory
    ports:
      - 3307:3306



